# Generated by Django 5.1.5 on 2025-01-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='programmingskill',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='projectexperience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='problem_solving',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='self_development',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='teamwork_experience',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
        migrations.DeleteModel(
            name='ProgrammingSkill',
        ),
        migrations.DeleteModel(
            name='ProjectExperience',
        ),
    ]
